### PR TITLE
Ddtload

### PR DESCRIPTION
**Pull request by allanjude**
### Motivation and Context
Writing to a dataset that has dedup enabled can perform very badly if the DDT entries that need to be modified are not loaded.

This is especially true after a reboot when none of the DDT is in the cache.

### Description
This introduces the new `zpool ddtload <poolname>` command

With the newer version of the patch, this command does not return until the operation is complete. The command is also now cancellable (control+c)

You can monitor the process with `zpool status -D` which now displays how much of the DDT is loaded.

Over time, other ARC cache items may push the DDT out of cache if it is not being heavily used. You can use the ddtload command again to refresh it.

### CODE REVIEW

**Comment by bgly** [comment]
I will do some preliminary testing today with this patch. - Thanks! I only have a system with ~1Gb dedup table, which isnt that big, but will see how it goes. If it goes well I'll have it ran on a system with 50Gb dedup table.

**Comment by allanjude** [comment]
> I will do some preliminary testing today with this patch. - Thanks! I only have a system with ~1Gb dedup table, which isnt that big, but will see how it goes. If it goes well I'll have it ran on a system with 50Gb dedup table.

We have been testing on a system with:
```
dedup: DDT entries 100451571, size 26.9G on disk, 15.2G in core (15.2G cached)

bucket              allocated                       referenced          
______   ______________________________   ______________________________
refcnt   blocks   LSIZE   PSIZE   DSIZE   blocks   LSIZE   PSIZE   DSIZE
------   ------   -----   -----   -----   ------   -----   -----   -----
     1    95.4M   54.6G   54.6G   54.6G    95.4M   54.6G   54.6G   54.6G
     2    97.3K   12.2G   12.2G   12.2G     230K   28.8G   28.8G   28.8G
     4     191K   23.8G   23.8G   23.8G     950K    119G    119G    119G
    32    97.7K   48.8M   48.8M   48.8M    4.63M   2.32G   2.32G   2.32G
 Total    95.8M   90.6G   90.6G   90.6G     101M    204G    204G    204G
```

**Comment by SidBB** [comment]
Quick question about the new formatting in `zpool status -D`. 

I see it now reports human-readable sizes. We have some orchestration/monitoring code that periodically parses that line to calculate DDT size. Will it honor the `-p` flag and display sizes in bytes if I run `zpool status -pD`? 

Or if we have to parse the human-readable sizes that's okay, just want to get an idea of the changes we'll need to make in the parsing code.

**Comment by bgly** [comment]
Running:
```
git checkout -b KlaraSystems-ddtload-sync spp-10.1.5
git pull git://github.com/KlaraSystems/zfs-spp.git ddtload-sync

```
When building I get:

```
../../module/zfs/ddt_zap.c:103:1: error: conflicting types for 'ddt_zap_loadall'                                                     │··························
 ddt_zap_loadall(ddt_t *ddt, objset_t *os, uint64_t object,                                                                          │··························
 ^                                                                                                                                   │··························
../../module/zfs/ddt_zap.c:59:1: note: previous definition of 'ddt_zap_loadall' was here                                             │··························
 ddt_zap_loadall(objset_t *os, uint64_t object)                                                                                      │··························
 ^                                                                                                                                   │··························
../../module/zfs/ddt_zap.c: In function 'ddt_zap_loadall':                                                                           │··························
../../module/zfs/ddt_zap.c:115:2: warning: 'return' with a value, in function returning void [enabled by default]                    │··························
  return (error);                                                                                                                    │··························
  ^                                                                                                                                  │··························
../../module/zfs/ddt_zap.c:113:1: warning: label 'out' defined but not used [-Wunused-label]                                         │··························
 out:                                                                                                                                │··························
 ^                                                                                                                                   │··························
../../module/zfs/ddt_zap.c:110:18: warning: unused variable 'attr' [-Wunused-variable]                                               │··························
  zap_attribute_t attr;                                                                                                              │··························
                  ^                                                                                                                  │··························
../../module/zfs/ddt_zap.c:108:14: warning: unused variable 'dde_search' [-Wunused-variable]                                         │··························
  ddt_entry_t dde_search;                                                                                                            │··························
              ^                                                                                                                      │··························
../../module/zfs/ddt_zap.c:106:15: warning: unused variable 'zc' [-Wunused-variable]                                                 │··························
  zap_cursor_t zc;                                                                                                                   │··························
               ^                                                                                                                     │··························
../../module/zfs/ddt_zap.c: At top level:                                                                                            │··························
../../module/zfs/ddt_zap.c:193:2: warning: initialization from incompatible pointer type [enabled by default]                        │··························
  ddt_zap_loadall,                                                                                                                   │··························
  ^                                                                                                                                  │··························
../../module/zfs/ddt_zap.c:193:2: warning: (near initialization for 'ddt_zap_ops.ddt_op_loadall') [enabled by default]               │··························
../../module/zfs/ddt_zap.c:59:1: warning: 'ddt_zap_loadall' defined but not used [-Wunused-function]                                 │··························
 ddt_zap_loadall(objset_t *os, uint64_t object)
../../module/zfs/ddt_zap.c:94:1: warning: 'ddt_zap_key_fill' defined but not used [-Wunused-function]                                │··························
 ddt_zap_key_fill(ddt_key_t *ddk, zap_attribute_t *za) 
```

**Comment by bgly** [comment]
I tried to build again and it shows:

../../module/zfs/dmu.c: In function 'dmu_object_cached_size':                                                                        │··························
../../module/zfs/dmu.c:1751:2: warning: implicit declaration of function 'bp_span_in_blocks' [-Wimplicit-function-declaration]       │··························
  uint8_t nbps = bp_span_in_blocks(dn->dn_indblkshift, 1); 

It seems like there is a missing patch for the new bp_span_in_blocks function?

**Comment by allanjude** [comment]
> 
> 
> Quick question about the new formatting in `zpool status -D`.
> 
> I see it now reports human-readable sizes. We have some orchestration/monitoring code that periodically parses that line to calculate DDT size. Will it honor the `-p` flag and display sizes in bytes if I run `zpool status -pD`?
> 
> Or if we have to parse the human-readable sizes that's okay, just want to get an idea of the changes we'll need to make in the parsing code.

The new patch does respect the -p flag

**Comment by allanjude** [comment]
> bp_span_in_blocks

That function was introduced upstream 7 months ago: https://github.com/zfsonlinux/zfs/commit/30af21b02569ac192f52ce6e6511015f8a8d5729

But it isn't in 0.8. I'll get that sorted for you.

**Comment by bgly** [comment]
Thanks! I see the new function in the redacted send/recv patch.

**Comment by allanjude** [comment]
> 
> 
> Thanks! I see the new function in the redacted send/recv patch.

I've merged the function over

**Comment by allanjude** [comment]
Have you completed a large load yet? How is it working?

**Comment by allanjude** [comment]
Can you measure the performance with this latest patch, and also tell us about the hardware it is running on.

There are limitations to the possible performance when using spinning disks because the DDT is made up of many small blocks scattered all over the disk. When using SSDs we are seeing quite high speeds when loading the DDT.

**Comment by bgly** [comment]
Will run and let you know.

**Comment by bgly** [comment]
> Can you measure the performance with this latest patch, and also tell us about the hardware it is running on.
> 
> There are limitations to the possible performance when using spinning disks because the DDT is made up of many small blocks scattered all over the disk. When using SSDs we are seeing quite high speeds when loading the DDT.

I was thinking if we used allocation classes and created a ddt one would that help and make that device an ssd?

**Comment by allanjude** [comment]
> 
> 
> 
> I was thinking if we used allocation classes and created a ddt one would that help and make that device an ssd?

Having the DDT live on an SSD definately helps in our testing

**Comment by bgly** [comment]
Are these the latest changes? -Thanks

**Comment by allanjude** [comment]
> 
> 
> Are these the latest changes? -Thanks

Yes, they improve peformance, and make 'zpool status -DD' cancellable using control+c, and fix the newly added `zpool status -DDp` test cases, that were using only 1 -D before

**Comment by bgly** [comment]
So far the testing has gone really well, doing some final stuff and then I will probably merge it tomorrow.

**Comment by bgly** [comment]
I just hit a state where zpool status -D was not cancellable. 

```
1580414322   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414322   spa_history.c:306:spa_history_log_sync(): command: zfs list -Hp -o compressratio,used,available,logicalused vpool1
1580414322   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414322   spa_history.c:306:spa_history_log_sync(): command: zpool list -Hp vpool1
1580414322   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414322   spa_history.c:306:spa_history_log_sync(): command: zpool list -Hp vpool1
1580414456   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414456   spa_history.c:306:spa_history_log_sync(): command: zpool status -DD
1580414527   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414527   spa_history.c:306:spa_history_log_sync(): command: zpool status -DD
1580414568   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414568   spa_history.c:306:spa_history_log_sync(): command: zpool status -DD
1580414589   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414589   spa_history.c:306:spa_history_log_sync(): command: zpool status -DD
1580414599   spa_history.c:339:spa_history_log_sync(): ioctl zpool_ddtload
1580414599   spa_history.c:306:spa_history_log_sync(): command: zpool load ddt vpool1
1580414604   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414604   spa_history.c:306:spa_history_log_sync(): command: zpool status -DD
1580414630   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414630   spa_history.c:306:spa_history_log_sync(): command: zfs list
1580414646   spa_history.c:339:spa_history_log_sync(): ioctl get_props
1580414646   spa_history.c:306:spa_history_log_sync(): command: zpool status -DD

[root@spplusc-7 sppdev]# zpool status -D
  pool: vpool1
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        vpool1      ONLINE       0     0     0
          sde       ONLINE       0     0     0
          sdf       ONLINE       0     0     0
        dedup
          sdg       ONLINE       0     0     0

errors: No known data errors

^C^C^C^C^C^C^C^C^C^C^C^C^Z^Z^Z^A^C^C^C

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11802 root      20   0       0      0      0 D  11.0  0.0   0:57.12 txg_sync
11290 root       0 -20       0      0      0 S   1.0  0.0   0:11.23 z_rd_int
11291 root       0 -20       0      0      0 S   1.0  0.0   0:11.36 z_rd_int
 3508 root      20   0  162324   4876   3856 R   0.7  0.0   0:00.03 top
11286 root       0 -20       0      0      0 S   0.7  0.0   0:11.01 z_rd_int
11288 root       0 -20       0      0      0 S   0.7  0.0   0:11.50 z_rd_int
11289 root       0 -20       0      0      0 S   0.7  0.0   0:10.90 z_rd_int
11294 root       0 -20       0      0      0 S   0.7  0.0   0:11.40 z_rd_int
11295 root       0 -20       0      0      0 S   0.7  0.0   0:11.07 z_rd_int
 3347 root      20   0       0      0      0 S   0.3  0.0   0:00.19 xfsaild/dm-0
11292 root       0 -20       0      0      0 S   0.3  0.0   0:11.23 z_rd_int
17212 sppdev    20   0  165884  10908   4392 S   0.3  0.0   0:01.33 mosh-server
    1 root      20   0  194092   8728   5684 S   0.0  0.0   0:01.74 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:10.04 kthreadd
    3 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_gp
    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_par_gp
    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:0H-kb
    8 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_wq
    9 root      20   0       0      0      0 S   0.0  0.0   0:00.02 ksoftirqd/0
   10 root      20   0       0      0      0 I   0.0  0.0   0:00.55 rcu_sched
   11 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh
   12 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/0

pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
vpool1      6.79T  3.42T  3.06K      0  7.39M      0
  sde       3.38T  1.60T      0      0      0      0
  sdf       3.38T  1.61T      0      0      0      0
dedup           -      -      -      -      -      -
  sdg       28.9G   219G  3.06K      0  7.39M      0
----------  -----  -----  -----  -----  -----  -----
              capacity     operations     bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
vpool1      6.79T  3.42T  2.80K      0  6.77M      0
  sde       3.38T  1.60T      0      0      0      0
  sdf       3.38T  1.61T      0      0      0      0
dedup           -      -      -      -      -      -
  sdg       28.9G   219G  2.80K      0  6.77M      0
----------  -----  -----  -----  -----  -----  -----
```

Nothing in dmesg showing hangs. This is using dedup allocation class.

**Comment by allanjude** [comment]
Only `zpool status -DD`, the part where we calculate the amount of the DDT that is loaded in memory (which can take a long time) is cancellable.

The regular `zpool status -D` is unmodified upstream now that we moved our code to -DD

If you are hung there, something else is going on.

**Comment by allanjude** [comment]
So you have a dedicated device to hold the DDT? Or is there still old DDT that is on the main pool too?

**Comment by bgly** [comment]
The above hang is from a dedicated device with newly written data so taht its not mixed.

**Comment by bgly** [comment]
Merged, so we can get a build to do testing for our next patch. - Will email if we hit any major issues.

**Pull request merged**
